const {getCount, increment, decrement} = require("./myCount")

console.log(getCount())
increment()
console.log(getCount())
decrement()
console.log(getCount())
increment()
increment()
increment()
increment()
console.log(getCount())
